[package]

# Project metadata
name = "rbpf"
version = "0.3.0"
authors = ["Quentin Monnet <qmo@qmon.net>"]

# Additional metadata for packaging
description = "Virtual machine and JIT compiler for eBPF programs"
repository = "https://github.com/qmonnet/rbpf"
readme = "README.md"
keywords = ["BPF", "eBPF", "interpreter", "JIT", "filtering"]
license = "Apache-2.0/MIT"

# Packaging directives
include = [
    "src/**",
    "examples/**",
    "tests/**",
    "bench/**",
    "LICENSE*",
    "Cargo.toml",
]

[profile.release]
# This is a typical set of options that helps Rust binaries stay small
lto = true
codegen-units = 1
opt-level = 3


[dependencies]

# Default features (std) are disabled so that the dependencies don't pull in the
# standard library when the crate is compiled for no_std
byteorder = { version = "1.2", default-features = false }
log = {version = "0.4.21", default-features = false }
combine = { version = "4.6", default-features = false }

# Optional Dependencies when using the standard library
libc = { version = "0.2", optional = true }
time = { version = "0.2", optional = true }

# Optional Dependencies for the CraneLift JIT
cranelift-codegen = { version = "0.99", optional = true }
cranelift-frontend = { version = "0.99", optional = true }
cranelift-jit = { version = "0.99", optional = true }
cranelift-native = { version = "0.99", optional = true }
cranelift-module = { version = "0.99", optional = true }

# Dependencies added for the ARMv7-eM JIT
num = { version = "0.4.2", default-features = false}
num-derive = { version = "0.4.2", default-features = false }
num-traits = { version = "0.2.18", default-features = false }
goblin = {version = "0.8.0", default_features = false , features = ["elf32", "elf64", "endian_fd"]}
libm = "0.2.8"

[dev-dependencies]

elf = "0.0.10"
json = "0.11"
hex = "0.4.3"

[features]
default = ["std"]
cargo-clippy = []
std = ["dep:time", "dep:libc", "combine/std"]
cranelift = [
    "dep:cranelift-codegen",
    "dep:cranelift-frontend",
    "dep:cranelift-jit",
    "dep:cranelift-native",
    "dep:cranelift-module",
]

# Examples that depend on the standard library should be disabled when
# testing the `no_std` configuration.
[[example]]
name = "disassemble"
required-features = ["std"]

[[example]]
name = "load_elf"
required-features = ["std"]

[[example]]
name = "uptime"
required-features = ["std"]

[[example]]
name = "to_json"

[[example]]
name = "rbpf_plugin"

[[example]]
name = "allowed_memory"
